server:
  port: 8001
  servlet:
    context-path: /

service:
  instance:
    id: ${random.int[1,50]}

spring:
  application:
      name: auth-service
  datasource:
    url: jdbc:h2:file:./h2-file-db/data/lighthouse;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration/h2
  h2:
    console:
      enabled: true
      path: /h2
# go to http://localhost:8001/h2 and enter jdbc:h2:file:/home/tsoyolv/projects/lighthouse/github/lighthouse/auth-service/h2-file-db/data/lighthouse

security:
  jwt:
    uri: /auth/**
    secret: 12k;msdfg/!@#$%sd
    expiration: "#{10*24*60*60}"

sms:
  serviceEnabled: false
  login: oleg.tcoi.work
  password: smsservicelhs1api
  https: true
  charset: utf-8
  debug: true
  post: false
  message:
    pattern:
      login: "Ваш пароль от LightHouse: %s. С праздничком!"

otp:
  prolongation:
    seconds: 300
  next-otp:
    timeout: 30
  default:
    password:
      enabled: true
      value: 1234

main-service:
  url: http://localhost:8002
  service-id: main-service

#spring.flyway.locations=classpath:/db/migration/postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver

# -------------- OLD ------------
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true
# spring.data.rest.base-path=/api
# spring.resources.static-locations=classpath:/templates/css,classpath:/templates/js,classpath:/templates/built,classpath:/templates/libraries,classpath:/templates/images
