server:
  port: 8001
  servlet:
    context-path: /login

spring:
  application:
      name: auth-service
  datasource:
    url: jdbc:h2:mem:lighthouse
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration/h2
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
# go to http://localhost:8001/h2 and enter jdbc:h2:mem:lighthouse

# --------------------------------------------- Shared properties ------------------------------------------------------

shared-folders:
    h2-db-file: /h2-file-db/data

security:
  jwt:
    uri: /auth/**
    secret: 12k;msdfg/!@#$%sd
    expiration: "#{10*24*60*60}"
    claims:
      authorities:
        claimName: authorities
      details:
        claimName: details
        userId: userId
        userBirthDate: userBirthDate
        userFirstName: userFirstName
        userSecondName: userSecondName
        userLastName: userLastName

sms:
  serviceEnabled: false
  login: oleg.tcoi.work
  password: smsservicelhs1api
  https: true
  charset: utf-8
  debug: true
  post: false
  message:
    pattern: "Ваш пароль для регистрации в LightHouse: %s."

otp:
  uri: /otp
  prolongation:
    seconds: 300
  next-otp:
    timeout: 30
  default:
    password:
      enabled: true
      value: 1234

crm-main-service:
  url: http://localhost:8002
  service-id: crm-main-service
  context-path: /crm-backend
  integration:
    uri:
      user: /integration/user

mobile-main-service:
  url: http://localhost:8004
  service-id: mobile-main-service
  context-path: ""
  integration:
    uri:
      user: /integration/user
