spring:
  datasource:
    url: jdbc:h2:mem:lighthouse
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration/h2
  h2:
    console:
      enabled: false

sms:
  serviceEnabled: false

otp:
  default:
    password:
      enabled: true
      value: 1234
